### ISSUE TITLE
Refactor leavesdb to have full repo as leaves and leavesdb as a package inside, along with model and data loading packages.

### ISSUE THREAD

**Issue by piperod** [JacobARose/pyleaves#1]
New library is named pyleaves, and contains leavesdb as a sub-package, along with several others for every stage of model training and evaluation.
-Jacob

**Comment by JacobARose** [comment]
leavesdb is now a sub-package within pyleaves! Our all purpose repo for leaf image database interaction, data preprocessing, model building and model training.

The original leavesdb will likely be deprecated in some way I've yet to decide.
