### ISSUE TITLE
Add README.md to leavesdb sub-package

### ISSUE THREAD

**Issue by JacobARose** [JacobARose/pyleaves#3]
Basic outline of how to get the most up-to-date database .json and/or .db file.

**Comment by piperod** [comment]
There is one issue here. If we save the file to local is taking too much space, but if I put it in data_cifs I get errors when opening it. I am researching how to solve this problem, in the mean time I will keep it in Home, but it is a concern for future usage.

**Comment by JacobARose** [comment]
I'm confused, the database file is taking up too much space? Checking "du -sh pyleaves" gives me 23 MB total for the repository, and that includes a leavesdb.db file in pyleaves/pyleaves/leavesdb/resources.

**Comment by piperod** [comment]
Documentation to create a db is on the readme. Also the file db is included in the repo under the resources folder.
